[uwsgi]
chdir = /opt/app

buffer-size = 65535

http-socket = 0.0.0.0:8000

http-enable-proxy-protocol = 1
http-auto-chunked = true
http-keepalive = 120
http-timeout = 120

processes = 3
module = src.wsgi:application

# Better startup/shutdown in docker
die-on-term = 1

master = 1
vacuum = 1

# Logging
logger-req = stdio
disable-logging = true
log-format = "(request_id=%(request_id)) (identity_user=%(identity_user) user_agent=%(uagent)) [%(ctime)] %(method) %(status) %(uri) %(rsize) B %(msecs) ms"

log-req-encoder = json {"source":"uwsgi-req", "data_tier":"FREQUENT", "message":"${msg}"}

py-autoreload = 3

max-requests = 150
